#!/bin/bash
# Script simples para verificar variáveis de ambiente

echo "=== VERIFICAÇÃO DE VARIÁVEIS ==="
echo "TELEGRAM_TOKEN: $TELEGRAM_TOKEN"
echo "PIXGO_API_KEY: $PIXGO_API_KEY"
echo "PIXGO_BASE_URL: $PIXGO_BASE_URL"
echo "DATABASE_URL: $DATABASE_URL"
echo "USDT_WALLET_ADDRESS: $USDT_WALLET_ADDRESS"
echo "SUBSCRIPTION_PRICE: $SUBSCRIPTION_PRICE"
echo "SUBSCRIPTION_DAYS: $SUBSCRIPTION_DAYS"
echo "LOG_LEVEL: $LOG_LEVEL"
echo "LOG_FILE: $LOG_FILE"
echo "PORT: $PORT"
echo "=== FIM VERIFICAÇÃO ==="