"""Initial migration

Revision ID: 3d57b5e29667
Revises: 
Create Date: 2025-10-28 12:36:01.731526

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d57b5e29667"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("telegram_id", sa.String(), nullable=False),
    sa.Column("username", sa.String(), nullable=True),
    sa.Column("first_name", sa.String(), nullable=True),
    sa.Column("last_name", sa.String(), nullable=True),
    sa.Column("status_assinatura", sa.String(), nullable=True),
    sa.Column("data_expiracao", sa.DateTime(), nullable=True),
    sa.Column("is_banned", sa.Boolean(), nullable=True),
    sa.Column("is_muted", sa.Boolean(), nullable=True),
    sa.Column("mute_until", sa.DateTime(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("telegram_id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
