"""Add USDT proof fields to Payment model

Revision ID: fc1f10031f07
Revises: fc68eb6a9eff
Create Date: 2025-11-04 08:10:48.896210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1f10031f07'
down_revision: Union[str, Sequence[str], None] = 'fc68eb6a9eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('proof_image_url', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('transaction_hash', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('proof_submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'proof_submitted_at')
    op.drop_column('payments', 'transaction_hash')
    op.drop_column('payments', 'proof_image_url')
    # ### end Alembic commands ###
